name: Build Test Win32 (Debug)

on:
  workflow_dispatch:

jobs:
  call-workflow-build:
    uses: ./.github/workflows/workflow-build-wtl-submodule.yml
    with:
      platform-arch: Win32
      build-config: Debug
